### ISSUE TITLE
Introduce Faker library

### ISSUE THREAD

**Issue by marcinkunert** [servettonga/Wr-52.TAQC-Java-TestProject#5]
Currently, the project has its own implementation of randomizing data, as shown in the snipped below.

https://github.com/servettonga/Wr-52.TAQC-Java-TestProject/blob/e7078fd432d86b4c36a169b118be3c90717e42c1/src/test/java/net/eventsexpress/app/utils/Utils.java#L15-L35

As mentioned by @ignatenko-paul it's a good idea to introduce [Faker](https://github.com/DiUS/java-faker) to do the job for you.

The goal of this issue is to replace the mentioned implementation with Faker.

**Comment by Thoughtseize1** [comment]
May I take this task?) If no one objects?

**Comment by servettonga** [comment]
> May I take this task?) If no one objects?

Sure. Gather an email, password(max 15 characters), maybe a username in case we can use it to edit profile.
