### ISSUE TITLE
Refactor ConfigurationManager

### ISSUE THREAD

**Issue by marcinkunert** [servettonga/Wr-52.TAQC-Java-TestProject#6]
1. The `configs` field could be an inline variable (inside the `getConfig()` method.
2. Instead of referencing it from the file `new File("src/test/resources/test.properties")` it would be better to use `Resource`, as it is more abstract and will work also if the project get's packaged in a `jar`

https://github.com/servettonga/Wr-52.TAQC-Java-TestProject/blob/e7078fd432d86b4c36a169b118be3c90717e42c1/src/test/java/net/eventsexpress/app/config/ConfigurationManager.java#L9-L25

**Comment by servettonga** [comment]
Done [#caa322c](https://github.com/servettonga/Wr-52.TAQC-Java-TestProject/commit/caa322ce7683baa8f7d96cc61d0a9912ee2e7c0a)

**Comment by marcinkunert** [comment]
@servettonga do not commit directly to `develop`, please do always create a new branch and pull request for your changes, even if they are really small
